shared: &shared
  host: localhost
  adapter: postgresql
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  database: corelogicdocs_development
  <<: *shared

test:
  database: corelogicdocs_test
  <<: *shared

production:
  database: corelogicdocs_production
  <<: *shared
